### ISSUE TITLE
Regenerator 1.12.1 Doesn't work

### ISSUE THREAD

**Issue by gaRt3n** [StargateMC/Regenerator#14]
[14:21:53] [Server thread/INFO]: [Regenerator] Enabling Regenerator v3.3.0
[14:21:53] [Server thread/ERROR]: Error occurred while enabling Regenerator v3.3.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
    at com.draksterau.Regenerator.Handlers.RLang.loadData(RLang.java:43) ~[?:?]
    at com.draksterau.Regenerator.Handlers.RLang.<init>(RLang.java:31) ~[?:?]
    at com.draksterau.Regenerator.RegeneratorPlugin.onEnable(RegeneratorPlugin.java:41) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.11.2.jar:git-Paper-1140]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [spigot-1.11.2.jar:git-Paper-1140]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot-1.11.2.jar:git-Paper-1140]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [spigot-1.11.2.jar:git-Paper-1140]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [spigot-1.11.2.jar:git-Paper-1140]
    at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [spigot-1.11.2.jar:git-Paper-1140]
    at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [spigot-1.11.2.jar:git-Paper-1140]
    at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [spigot-1.11.2.jar:git-Paper-1140]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [spigot-1.11.2.jar:git-Paper-1140]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [spigot-1.11.2.jar:git-Paper-1140]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[14:21:53] [Server thread/INFO]: [Regenerator] Disabling Regenerator v3.3.0

**Comment by StargateMC** [comment]
Hi @gaRt3n,

Regenerator v3.3.0 will never support 1.12. It deprecates a lot of code designed to deal with configuration files so you'll have to wait til v4.0. Sorry!

Bysokar

**Comment by gaRt3n** [comment]
When will it be released? It was really great!

**Comment by StargateMC** [comment]
Hi @gaRt3n You probably are long past caring, but I've just pushed an update to SpigotMC for 1.15.2 support.
