### ISSUE TITLE
Redprotect

### ISSUE THREAD

**Issue by daniorio** [StargateMC/Regenerator#16]
Please fix work for last version of this plugin with RedProtect v7.5.5 api. Minecraft 1.7.10, And sorry for my english, i'm from Russia.

java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/API/RedProtectAPI
	at com.draksterau.Regenerator.integration.RedProtectIntegration.claimExists(RedProtectIntegration.java:166) ~[?:?]
	at com.draksterau.Regenerator.integration.RedProtectIntegration.validateConfig(RedProtectIntegration.java:80) ~[?:?]
	at com.draksterau.Regenerator.Handlers.RUtils.loadIntegrationFor(RUtils.java:382) ~[?:?]
	at com.draksterau.Regenerator.Handlers.RUtils.loadIntegrations(RUtils.java:433) ~[?:?]
	at com.draksterau.Regenerator.RegeneratorPlugin.onEnable(RegeneratorPlugin.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by StargateMC** [comment]
Hi Daniorio, Please have the RedProtect developer see the change notes I made for the latest official release. They can make it so integration doesn't break ever again with about 10 minutes of work :)
