### ISSUE TITLE
Contributing with a translation

### ISSUE THREAD

**Issue by TheUndermon** [StargateMC/Regenerator#20]
I want to contribute with a portuguese translation, but there is no explicit lang folder. Should i create a messages_pt.yml as an alternative file option?

**Comment by StargateMC** [comment]
@Undermmon If you like, then I'll add in a function to have Regenerator support switching between locales rather than have people need to replace messages.yml with another from somewhere else. 

Much appreciated :)

**Comment by StargateMC** [comment]
Hi @Undermmon Please see attached a quick build of v3.4.4.
This supports configuring of a language in config, and adds a lang folder.

You may need to rename it to .jar, not .zip though. It wouldnt let me upload.

Language in config should be the filename without .yml on it... so for ENGLISH.yml its just ENGLISH.

Feel free to have a play around and let me know how you go.

Regards,

Bysokar

[Regenerator.zip](https://github.com/StargateMC/Regenerator/files/4351800/Regenerator.zip)

**Comment by StargateMC** [comment]
Will be moving more messages to lang soon. some are still hardcoded.

**Comment by TheUndermon** [comment]
I am getting a crash on this 3.4.4. I'm using Paper 132, but it works fine on 3.4.1.

`[11:23:07 INFO]: [Regenerator] Enabling Regenerator v3.4.4*
[11:23:07 ERROR]: Error occurred while enabling Regenerator v3.4.4 (Is it up to date?)
java.lang.NullPointerException: null
	at com.draksterau.Regenerator.Handlers.RLang.loadData(RLang.java:37) ~[?:?]
	at com.draksterau.Regenerator.Handlers.RLang.<init>(RLang.java:32) ~[?:?]
	at com.draksterau.Regenerator.RegeneratorPlugin.onEnable(RegeneratorPlugin.java:43) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-132]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-132]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-132]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-132]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-132]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-132]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
`

**Comment by StargateMC** [comment]
Hi @Undermmon I've fixed v3.4.4, i'll post a version with the lang entries so far on spigotmc.org shortly. You'll be able to expand Portuguese as I expand the english lang over the next few days if you like =)

**Comment by TheUndermon** [comment]
Great. I'll update it when available.
