### ISSUE TITLE
Updating Regenerator from v3.4.3 to v3.4.4 leads causes Regenerator to crash

### ISSUE THREAD

**Issue by StargateMC** [StargateMC/Regenerator#22]
`[04:30:12 ERROR]: Error occurred while enabling Regenerator v3.4.4 (Is it up to date?)
java.lang.NullPointerException: null
        at com.draksterau.Regenerator.Handlers.RConfig.updateConfig(RConfig.java:196) ~[?:?]
        at com.draksterau.Regenerator.Handlers.RConfig.loadData(RConfig.java:121) ~[?:?]
        at com.draksterau.Regenerator.Handlers.RConfig.<init>(RConfig.java:97) ~[?:?]
        at com.draksterau.Regenerator.RegeneratorPlugin.getOrInitConfig(RegeneratorPlugin.java:47) ~[?:?]
        at com.draksterau.Regenerator.RegeneratorPlugin.onEnable(RegeneratorPlugin.java:55) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-105]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-105]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-105]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-105]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-105]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-105]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Comment by StargateMC** [comment]
Resolved with v3.5.0.
