### ISSUE TITLE
Not loading on 1.13.2

### ISSUE THREAD

**Issue by TomLewis** [StargateMC/Regenerator#28]
```[15:28:34] [Server thread/ERROR]: Error occurred while enabling Regenerator v3.5.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_15_R1/MinecraftServer
	at com.draksterau.Regenerator.RegeneratorPlugin.onEnable(RegeneratorPlugin.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-655]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_15_R1.MinecraftServer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-655]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 12 more
```

**Comment by Bysokar** [comment]
Regenerator doesnt support v1.13 sorry. I have no plans to support this either. I skipped from 1.10 to 1.15. I'm looking at releasing 1.20.1 shortly though.

**Comment by TomLewis** [comment]
Oh fantastic, im running 1.18.2 atm, but future plans to move to 1.20 when more plugins update.
